gitea:
  config:
    database:
      DB_TYPE: postgres
      HOST: postgres
      NAME: giteadb
      USER: gitea
      PASSWD: password
  additionalConfigSources:
    - configMap:
        name: gitea-app-ini-plaintext
  admin:
    username: admin
    password: password
    email: email

image:
  repository: gitea
  tag: 1.24.2

postgresql:
  enabled: false

postgresql-ha:
  enabled: false

redis-cluster:
  enabled: false

redis:
  enabled: false

persistence:
  enabled: true
  accessModes: ["ReadWriteMany"]
  size: "10Gi"

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 512Mi

ingress:
  enabled: true
  annotations:
    spec.ingressClassName: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: "acme-issuer"
  hosts:
    - host: git.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: gitea-tls-cert
      hosts:
        - "*.example.com"

actions:
  enabled: true
  runner:
    replicas: 3
  provisioning:
    enabled: true
