version: "3"
services:  
  jackett:
    image: "linuxserver/jackett"
    container_name: "jackett"
    env_file:
        ./.env
    volumes:
      - ${DOCKERDIR}/appdata/jackett:/config
      - ${DATADIR}/downloads:/downloads
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "9117:9117"
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
