apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: immich-migration-db
spec:
  serviceName: "immich-migration-db"
  replicas: 1
  selector:
    matchLabels:
      app: immich-migration-db
  template:
    metadata:
      labels:
        app: immich-migration-db
    spec:
      containers:
        - name: postgres
          image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: immich
            - name: POSTGRES_USER
              value: immich
            - name: POSTGRES_PASSWORD
              value: arsehole
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: immich-migration-db
spec:
  selector:
    app: immich-migration-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: LoadBalancer