apt_packages:
  - curl
  - vim
  - htop
  - wireguard

wireguard_path: "/etc/wireguard"
wireguard_interface: "wg0"
wireguard_private_key_file: "{{ wireguard_path }}/server_private.key"
wireguard_public_key_file: "{{ wireguard_path }}/server_public.key"
wg_port: 51820
wg_address: "10.0.0.1/24"
wg_dns: "1.1.1.1"
wg_peers:
  - public_key: "LburMRtqT5LK0K1xzGGh4VkNVgWZQRm96dsxf6twbkw="
    allowed_ips: "0.0.0.0/0"
    endpoint: "tahmidcloud.com:51820"
    persistent_keepalive: 25
