# filepath: /home/taqi/homeserver/k3s-infra/cert-manager/templates/clusterIssuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.name }}
  namespace: {{ .Values.namespace }}
spec:
  acme:
    server: {{ .Values.clusterIssuer.server }}
    privateKeySecretRef:
      name: {{ .Values.clusterIssuer.privateKeySecretRef }}
    solvers:
    - dns01:
        cloudflare:
          email: {{ .Values.clusterIssuer.email }}
          apiTokenSecretRef:
            name: {{ .Values.clusterIssuer.apiTokenSecretRef.name }}
            key: {{ .Values.clusterIssuer.apiTokenSecretRef.key }}