apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: immich-minio-store
spec:
  configuration:
    destinationPath: s3://immich
    endpointURL: ${MINIO_ENDPOINT_URL}
    s3Credentials:
      accessKeyId:
        name: minio-creds
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: minio-creds
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
    data:
      compression: gzip
  retentionPolicy: "15d"
