---
# Secret for MinIO credentials
apiVersion: v1
kind: Secret
metadata:
  name: minio-creds
type: Opaque
stringData:
  ACCESS_KEY_ID: ${MINIO_ACCESS_KEY_ID}
  ACCESS_SECRET_KEY: ${MINIO_ACCESS_SECRET_KEY}
