apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library-pv
  labels:
    app: local
spec:
  capacity:
    storage: 900Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /media/immich # Path to your NFS share
    server: "${NFS_SERVER}"        # IP of your NFS server (replace with correct IP)
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 900Gi
  selector:
    matchLabels:
      app: local