apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.claimName }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{  .Values.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
