apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-nfs-pv
  labels:
    app: media
spec:
  capacity:
    storage: 900Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /media/flexdrive # Path to your NFS share
    server: "${NFS_SERVER}"        # IP of your NFS server (replace with correct IP)
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
