apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Storage for Jellyfin config files
  storageClassName: longhorn  # Make sure this matches your Longhorn storage class
