apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 900Gi
  storageClassName: manual
  selector:
    matchLabels:
      app: media
