# longhorn-3x.yaml (High Availability)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-2x
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880" # 48 hours in minutes (optional)
  fsType: "ext4"
allowVolumeExpansion: true
