when:
  - event: push
  - branch: *

steps:
  - name: build
    image: ubuntu:22.04
    commands:
      - echo "This is the build step"
      - echo "binary-data-123" > executable
  - name: a-test-step
    image: golang:1.24
    commands:
      - echo "Testing ..."
      - go version
