when:
  - branch: master
    event: push
    event: pull_request
  - branch: feature/*
    event: push

steps:
  - name: build
    image: ubuntu:22.04
    commands:
      - echo "This is the build step"
      - echo "binary-data-123" > executable
  - name: a-test-step
    image: golang:1.24
    commands:
      - echo "Testing ..."
      - go version
